language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - mkdir -p build/logs
  - composer install

script:
  - ./vendor/bin/phpunit --debug --stop-on-error --stop-on-failure

after_success:
 - travis_retry php vendor/bin/php-coveralls -v
